### PR TITLE
SCOPE_ASSERT_EQUAL now compares char*, nullptr

### PR DESCRIPTION
**Pull request by zweger**

### CODE REVIEW

**Comment by zweger** [comment]
I've updated this PR to disable the sequence-based `evalEqualImpl` on `std::string`, to provide a better failure message.

**Comment by jonstewart** [comment]
I'm not convinced that all the type computing is worth being able to support mixed equality comparisons of `std::string` and C strings. The alternative construction is just:
```
std::string expected = "hello";
SCOPE_ASSERT_EQUAL(s, std::string(foo.a_c_string));
```

C++ does not support mixed equality comparisons of `std::string` and C strings for a reason, and Scope has heretofore followed its lead. The ease of the above alternative is why this mechanism did not exist prior to this PR. Why is it necessary?

_Especially_, why is the `printValue` stuff necessary?

**Comment by zweger** [comment]
> I'm not convinced that all the type computing is worth being able to support mixed equality comparisons of std::string and C strings. 

Current scope supports mixed equality comparisons of std::string and C strings. This PR doesn't change that.

```
SCOPE_TEST(CharPtrEquality) {
  const char* a = "hello";
  std::string b = "hello";

  SCOPE_ASSERT_EQUAL(a, b);
}
```

> Especially, why is the printValue stuff necessary?

Because `operator<<(std::nullptr_t)` doesn't compile. I see some references online that it should work in C++17, but it doesn't seem to work on my system. Go figure.

**Comment by jonstewart** [comment]
I used explicit specialization on char* instead. See https://github.com/jonstewart/scope/pull/23.

**Pull request closed without merging**
